import type { V3PreviewData } from "./types";

export const v3PreviewData: V3PreviewData = {
  marketPulse: {
    session: "VN MARKET · POST-CLOSE INTEL",
    freshness: "Fresh 04m ago",
    vnindex: "1,286.42",
    vnindexDelta: 1.34,
    regime: "RISK-ON ROTATION",
    breadth: 68.2,
    volatility: "Contained",
    watchState: "11 symbols armed",
  },
  decision: {
    mode: "TRADE",
    confidence: 82,
    primaryReason: "Trend continuation with broad participation and healthy pullback structure.",
    highestQualitySetup: "FPT A+ Breakout Pullback",
    mainRisk: "If breadth breaks below 52%, momentum setups lose edge quickly.",
    nextAction: "Deploy 2 staggered entries from Tier A stack before open+30m window.",
    riskPosture: "Measured Aggression",
    capitalProtection: "Kill-switch if breadth < 52% or VNINDEX loses 1,272 pivot close.",
  },
  radarItems: [
    {
      symbol: "FPT",
      tier: "A+",
      readiness: 93,
      risk: 28,
      signal: 91,
      status: "qualified",
      reason: "Pullback hold + volume reclaim",
    },
    {
      symbol: "TCB",
      tier: "A",
      readiness: 88,
      risk: 34,
      signal: 84,
      status: "qualified",
      reason: "Breakout retest in zone",
    },
    {
      symbol: "HPG",
      tier: "B",
      readiness: 74,
      risk: 46,
      signal: 73,
      status: "near-miss",
      reason: "Needs one more constructive close",
    },
    {
      symbol: "SSI",
      tier: "WATCH",
      readiness: 61,
      risk: 55,
      signal: 66,
      status: "near-miss",
      reason: "Volume confidence not confirmed",
    },
    {
      symbol: "MWG",
      tier: "REJECT",
      readiness: 38,
      risk: 72,
      signal: 44,
      status: "rejected",
      reason: "Extended >8% from valid trigger",
    },
  ],
  setupCards: [
    {
      symbol: "FPT",
      tier: "A+",
      setupType: "Breakout Pullback",
      entry: "128.4 - 129.2",
      stop: "124.8 (-3.2%)",
      riskToReward: "1 : 2.7",
      confidence: 89,
      health: "Healthy",
      blocker: "None",
      actionState: "EXECUTE WINDOW OPEN",
    },
    {
      symbol: "TCB",
      tier: "A",
      setupType: "Support Reclaim",
      entry: "50.1 - 50.6",
      stop: "48.4 (-3.5%)",
      riskToReward: "1 : 2.2",
      confidence: 84,
      health: "Healthy",
      blocker: "Position sizing sync pending",
      actionState: "ARMED",
    },
    {
      symbol: "HPG",
      tier: "B",
      setupType: "Trend Continuation",
      entry: "31.8 trigger",
      stop: "30.4 (-4.4%)",
      riskToReward: "1 : 1.6",
      confidence: 72,
      health: "Warning",
      blocker: "Relative volume still below threshold",
      actionState: "WATCH FOR CONFIRM",
    },
    {
      symbol: "MWG",
      tier: "WATCH",
      setupType: "Late Breakout",
      entry: "Deferred",
      stop: "N/A",
      riskToReward: "N/A",
      confidence: 45,
      health: "Blocked",
      blocker: "Chasing risk invalidates setup quality",
      actionState: "DO NOT TRADE",
    },
  ],
  risk: {
    currentExposure: 41,
    maxRisk: 60,
    openPositions: 3,
    lossLimit: "-2.0R daily hard stop",
    posture: "Measured Aggression",
    blockers: [
      "Do not add risk if first hour breadth collapses below 52%",
      "No averaging down on failed breakout symbols",
      "Pause all new entries after two invalidations in same session",
    ],
    capitalProtectionState: "Capital shield ACTIVE",
  },
  ledger: {
    wins: 3,
    losses: 1,
    openTrades: 3,
    pnlPulse: "+1.8R · last 5 sessions",
    reviewQueue: 5,
    disciplineScore: 93,
  },
  evidence: [
    { label: "Scanner Diagnostics", value: "Universe 382 · Qualified 14 · Tier A 4", state: "ok" },
    { label: "Data Freshness", value: "OHLCV synced 16:07 ICT · latency 73ms", state: "ok" },
    { label: "Market Blockers", value: "None critical · 2 soft warnings", state: "warn" },
    { label: "Technical Evidence", value: "Breadth expansion + trend compliance 0.78", state: "ok" },
    { label: "Macro Shock Risk", value: "US futures event in 9h", state: "danger" },
  ],
  pulseSeries: [12, 15, 14, 18, 22, 21, 24, 27, 25, 29, 32, 31, 34, 37, 40, 42, 39, 43],
};
